produits_data = {
    "Clémentine": {"stock": 6, "prix": 2.90, "unite": "kg", "categorie": "fruit"},
    "Datte": {"stock": 4, "prix": 7.00, "unite": "kg", "categorie": "fruit"},
    "Grenade": {"stock": 3, "prix": 3.50, "unite": "kg", "categorie": "fruit"},
    "Kaki": {"stock": 3, "prix": 4.50, "unite": "kg", "categorie": "fruit"},
    "Kiwi": {"stock": 5, "prix": 3.50, "unite": "kg", "categorie": "fruit"},
    "Mandarine": {"stock": 6, "prix": 2.80, "unite": "kg", "categorie": "fruit"},
    "Orange": {"stock": 8, "prix": 1.50, "unite": "kg", "categorie": "fruit"},
    "Pamplemousse": {"stock": 8, "prix": 2.00, "unite": "pièce", "categorie": "fruit"},
    "Poire": {"stock": 5, "prix": 2.50, "unite": "kg", "categorie": "fruit"},
    "Pomme": {"stock": 8, "prix": 1.50, "unite": "kg", "categorie": "fruit"},
    "Carotte": {"stock": 7, "prix": 1.30, "unite": "kg", "categorie": "legume"},
    "Choux de Bruxelles": {"stock": 4, "prix": 4.00, "unite": "kg", "categorie": "legume"},
    "Chou vert": {"stock": 12, "prix": 2.50, "unite": "pièce", "categorie": "legume"},
    "Courge butternut": {"stock": 6, "prix": 2.50, "unite": "pièce", "categorie": "legume"},
    "Endive": {"stock": 5, "prix": 2.50, "unite": "kg", "categorie": "legume"},
    "Épinard": {"stock": 4, "prix": 2.60, "unite": "kg", "categorie": "legume"},
    "Poireau": {"stock": 5, "prix": 1.20, "unite": "kg", "categorie": "legume"},
    "Potiron": {"stock": 6, "prix": 2.50, "unite": "pièce", "categorie": "legume"},
    "Radis noir": {"stock": 10, "prix": 5.00, "unite": "pièce", "categorie": "legume"},
    "Salsifis": {"stock": 3, "prix": 2.50, "unite": "kg", "categorie": "legume"},
}